# Generated by Django 5.2.11 on 2026-03-18 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('capture_address', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('scope_label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ambiguous', 'Ambiguous'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='email_ingestion.project')),
            ],
            options={
                'db_table': 'checkpoints',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('ingested_via', models.CharField(choices=[('forward', 'Forward'), ('upload', 'Upload')], default='forward', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('text_content', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='email_ingestion.checkpoint')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='email_ingestion.project')),
            ],
            options={
                'db_table': 'artifacts',
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('summary_text', models.TextField()),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ambiguous', 'Ambiguous'), ('blocked', 'Blocked')], max_length=20)),
                ('checkpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='email_ingestion.checkpoint')),
            ],
            options={
                'db_table': 'snapshots',
            },
        ),
    ]
