# Generated by Django 5.2.12 on 2026-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='waiting_on',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
