# Generated by Django 5.2.12 on 2026-03-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ingestion', '0003_project_address_project_project_number_project_sqft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='thread_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
